-- V1: initial schema based on DTOs (students, academic_info, preferences and collections)

CREATE TABLE IF NOT EXISTS students (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    nombre VARCHAR(255),
    edad INT,
    correo VARCHAR(255),
    telefono VARCHAR(50),
    ciudad_residencia VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS academic_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(36) NOT NULL,
    programa VARCHAR(255),
    semestre_actual INT,
    promedio_acumulado DOUBLE,
    detalle_materias TEXT,
    CONSTRAINT fk_academic_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS academic_materias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_info_id BIGINT NOT NULL,
    materia VARCHAR(255),
    CONSTRAINT fk_mat_academic FOREIGN KEY (academic_info_id) REFERENCES academic_info(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS student_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(36) NOT NULL,
    modalidad_estudio VARCHAR(255),
    notificaciones TEXT,
    CONSTRAINT fk_pref_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS preferences_actividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preference_id BIGINT NOT NULL,
    actividad VARCHAR(255),
    CONSTRAINT fk_act_pref FOREIGN KEY (preference_id) REFERENCES student_preferences(id) ON DELETE CASCADE
);

-- Optional indexes
CREATE INDEX IF NOT EXISTS idx_academic_student ON academic_info(student_id);
CREATE INDEX IF NOT EXISTS idx_pref_student ON student_preferences(student_id);
